FROM dockerhub.hd123.com/jre-alpine:7-bash

RUN mkdir -p /opt/heading/ && \
	cd /opt/heading/ && \
	curl "http://download.hd123.com/TmpFiles/TA/20170703/azkaban-executor-server-2.5.0.tar.gz" | tar xz -C /opt/heading/ && \
	mv azkaban-executor-2.5.0 azkaban-executor && \
	curl "http://download.hd123.com/TmpFiles/TA/20170623.2/mysql-connector-java-5.1.35.tar.gz" | tar xz -C /opt/heading/ && \
	mv mysql-connector-java-5.1.35 mysql-connector-java && \
	mv mysql-connector-java/mysql-connector-java-5.1.35-bin.jar azkaban-executor/extlib/ && \
	rm -rf mysql-connector-java && \
	sed -i "s/&//" azkaban-executor/bin/azkaban-executor-start.sh && \
	wget -P /opt/heading/ http://download.hd123.com/TmpFiles/TA/20170626.3/run.sh
	
ENTRYPOINT sh /opt/heading/run.sh