FROM dockerhub.hd123.com/jre-alpine:7-mysql

RUN mkdir -p /opt/heading/ && \
	cd /opt/heading/ && \
	curl "http://download.hd123.com/TmpFiles/TA/20170703/azkaban-web-server-2.5.0.tar.gz" | tar xz -C /opt/heading/ && \
	mv azkaban-web-2.5.0 azkaban-web && \
	curl "http://download.hd123.com/TmpFiles/TA/20170623.6/keystore.tar.gz" | tar xz -C /opt/heading/azkaban-web && \
	curl "http://download.hd123.com/TmpFiles/TA/20170623.2/mysql-connector-java-5.1.35.tar.gz" | tar xz -C /opt/heading/ && \
	mv mysql-connector-java-5.1.35 mysql-connector-java && \
	mv mysql-connector-java/mysql-connector-java-5.1.35-bin.jar azkaban-web/extlib/ && \
	rm -rf mysql-connector-java && \
	mkdir azkaban-web/logs/ && \
	sed -i "s/&//" azkaban-web/bin/azkaban-web-start.sh && \
	wget -P /opt/heading/ http://download.hd123.com/TmpFiles/TA/20170627.2/run.sh
	
ENTRYPOINT sh /opt/heading/run.sh
